spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assessor
    username: assessor
  password: assessor
  jpa:
    hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      format_sql: true
  open-in-view: false
  flyway:
    enabled: true
server:
  port: 8080


springdoc:
api-docs:
  path: /v3/api-docs
swagger-ui:
  path: /swagger-ui.html